### PR TITLE
Add JSON.parse(...) to the afterFind and afterFetch hooks for a model.

### PR DESCRIPTION
**Pull request by thsteinmetz**

### CODE REVIEW

**Comment by watzon** [comment]
Very good. Thanks for the PR!

**Comment by thsteinmetz** [comment]
Glad to help, @watzon !! Would you be able to make a release with the update?

**Comment by watzon** [comment]
Sure thing @thsteinmetz

**Comment by thsteinmetz** [comment]
Thanks, @watzon !! Looking forward to using this in my app!

**Pull request merged**
